In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [4]:
boston=load_boston()

In [60]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [61]:
x=boston.data
y=boston.target

In [62]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [63]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
       17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
       25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
       23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
       32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
       34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
       20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
       26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
       31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
       22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
       42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
       36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
       32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
       20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
       20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
       22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
       21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
       19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
       32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
       18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
       16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
       13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
        7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
       12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
       27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
        8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
        9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
       10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
       15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
       19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
       29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
       20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
       23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)
# 80% data for training and 20% data for testing

In [70]:
# applying Liner Regresion
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [71]:
y_pred=reg.predict(x_test)
y_pred

array([13.76450373, 14.15532252, 12.39123593, 20.81398649, 19.35594307,
       25.07142213, 19.26685428, 36.41838955, 29.71583368, 11.89249585,
       18.9118846 , 16.76053853, 25.89726739, 27.16162168, 32.83379838,
       23.54341663, 16.16777106, 21.64324252, 18.48613324, 20.34019477,
       25.29440346, 35.97623588, 11.09735266, 27.5852319 , 30.40023071,
       15.72925113, 23.88353064, 16.66019472, 27.01354775, 29.49605851,
       22.2081783 , 13.02701976, 14.30970332, 24.82890454,  6.67808302,
       15.13311669, 23.86422849, 30.75529942, 26.44357677, 22.03241409,
       19.72173059, 13.62403678, 27.20895022, 19.39992878, 22.98925564,
       25.08674086, 20.88309131, 27.25326877, 22.30918114, 20.47302424,
       36.37134404, 13.08062401, 28.86462845,  9.85497374, 16.78301064,
       22.45813613, 24.95983473, 12.3679725 , 23.79263438,  7.63449889,
       22.39156689, 12.644099  , 20.2663564 , 23.77717   , 25.39170378,
       27.40561337, 36.42282126, 12.73046689, 26.7872484 , 10.60661937,
        6.86360873, 23.40607336, 34.15554692, 29.03186863, 37.11294973,
        7.25453083, 19.48498751, 28.8330415 , 19.04821402, 24.26866324,
       14.95186939, 23.43616294, 14.67732927, 23.68557987, 20.78591543,
       36.8345838 , 25.29126893,  2.17563147, 14.40846721, 22.60033171,
       14.50425789, 28.94931797, 29.35652213,  7.38885851, 13.03805581,
       27.13668506, 25.82430228, 20.40938962, 28.20405434,  1.58572406,
       24.71611346, 26.19357919])

In [72]:
y_test

array([15.4, 13.1, 13.5, 16.7, 22.9, 23.1, 17.1, 38.7, 23.6,  5.6, 17.1,
       17.5, 29.8, 23.9, 33.2, 24.7, 13.4, 18.7, 17.5, 20.4, 25.3, 35.1,
       15.6, 22.6, 30.1, 17.6, 30.1, 13.8, 23.3, 32.9, 17.4, 14. ,  8.4,
       19.4, 10.4, 18.4, 24.4, 34.7, 24.8, 22.2, 18.6, 14.5, 22.1, 18.4,
       21.2, 25. , 19.6, 27.1, 21.2, 19.3, 33.4, 13.9, 22.8,  9.7, 23.1,
       17.8, 24.3, 13.6, 24.4, 11.8, 20.3, 18.2, 19.5, 22.2, 28.7, 25.2,
       42.3, 18.5, 22.3, 15.2,  7. , 19.6, 26.7, 25. , 44. ,  8.5, 14.6,
       24.4, 27.1, 18.9, 20.6, 21. , 16.2, 23. , 24.5, 50. , 24.2,  8.1,
       27.5, 21.9, 15.7, 34.9, 42.8, 14.6,  8.3, 23.7, 26.5, 19.9, 26.6,
       17.9, 23.3, 23.8])

In [74]:
# mean square error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

20.037388539019354